#!/usr/bin/python3
import sys
from save_to_json_file import save_to_json_file
from load_from_json_file import load_from_json_file

def add_items_to_list(args):
    try:
        existing_list = load_from_json_file("add_item.json")
    except FileNotFoundError:
        existing_list = []

    updated_list = existing_list + args
    save_to_json_file(updated_list, "add_item.json")

if __name__ == "__main__":
    args_to_add = sys.argv[1:]
    add_items_to_list(args_to_add)
